## YAML Template.
---
language: java
jdk: oraclejdk8

notifications:
  slack:
    on_success: never
    on_failure: always

cache:
  directories:
    - $HOME/.m2

script:
    - mvn verify -Ptest
    
after_success:

    - mvn tomcat7:deploy -Premote